---
title: "plot test"
author: "Shijia Zhang"
date: "2024-04-08"
output: html_document
---

```{r}
source("adm_helper.R")
source("adm_main.R")
source("adm_summary.R")
library(dplyr)
library(plotly)
library(htmlwidgets)
library(tidyr)
library(data.table)
library(readxl)
```

```{r}
library(lubridate)
path = "/Users/shijia.zhang/Desktop/ADNI/ADMerge/R/data"

src_table <- get_src_table(path = path, ID_pattern = "Subject", ID_usr_list = c("Subject"),DATE_usr_list = c("Acq.Date"))

src_table

plot <- plot.files(path, FILE_pattern = ".xlsx|.xls|.csv", dict_src = src_table) 

plot
```


```{r}
library(dplyr)
library(ggplot2)

data <- read.csv("/Users/shijia.zhang/Desktop/ADNI_Phase2/merged_3yrs_data.csv")

data %>% filter(`Subject` == "027_S_0485")

data %>% group_by(Subject) %>% arrange(Subject) %>% mutate(rowid = row_number())%>% head(500)%>% ggplot(aes(x = rowid , y = Subject, color = Group)) + geom_point()

# Merge diagnosis. 

# Exclude AD， 重新train model, 重新画map CN vs. MCI
# order loss (optional) 3 class

# 1. FSL and Skull striper(nbsl)
# 2. Make sure JHPCE and GPU can run
# CC Zheyu

data %>% filter(Subject == "133_S_1055")

data %>% filter(Group == "AD")

data %>% distinct(Subject)

data

```



